<?php

namespace PIGBundle\Repository;

/**
 * CateringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CateringRepository extends \Doctrine\ORM\EntityRepository
{
}
