<?php

namespace PIGBundle\Repository;

/**
 * LimpiezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimpiezaRepository extends \Doctrine\ORM\EntityRepository
{
}
