<?php

namespace PIGBundle\Repository;

/**
 * MantenimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MantenimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
